# Pandas

        1. Series               -> 1-D data / 1-D array
        2. Dataframe            -> collection of series / 2-D data / spreadsheet like object 
        3. Pannels              -> multidimensional data

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
s1 = pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
arr = np.array([324,45,67,78,56])
arr

array([324,  45,  67,  78,  56])

In [5]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
s1.ndim

1

In [7]:
s1.shape

(5,)

In [8]:
s1.size

5

In [9]:
s1.dtype

dtype('int64')

In [10]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [11]:
s1[0]

np.int64(10)

In [12]:
arr

array([324,  45,  67,  78,  56])

In [13]:
arr[-1]

np.int64(56)

In [13]:
s1[-1]

KeyError: -1

In [14]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [15]:
arr

array([324,  45,  67,  78,  56])

In [16]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [17]:
s1[0]

np.int64(10)

In [18]:
s1 = pd.Series([10,20,30,40,50], index=['A', 'B', 'C', 'D', 'E'])
s1

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [19]:
s1

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [20]:
s1[0]

C:\Users\Mayan\AppData\Local\Temp\ipykernel_25164\643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]


np.int64(10)

In [21]:
s1[-1]

C:\Users\Mayan\AppData\Local\Temp\ipykernel_25164\149126795.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[-1]


np.int64(50)

In [22]:
s1['E']

np.int64(50)

In [23]:
s1['B']

np.int64(20)

In [24]:
s1

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [25]:
s1[4]

C:\Users\Mayan\AppData\Local\Temp\ipykernel_25164\3229368127.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[4]


np.int64(50)

In [26]:
s1

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [27]:
s1['A'] = 100

In [28]:
s1

A    100
B     20
C     30
D     40
E     50
dtype: int64

In [29]:
s1[:3]

A    100
B     20
C     30
dtype: int64

In [30]:
s1['A':'D']

A    100
B     20
C     30
D     40
dtype: int64

In [31]:
s1

A    100
B     20
C     30
D     40
E     50
dtype: int64

In [32]:
s1.mean()

np.float64(48.0)

In [33]:
s1.sum()

np.int64(240)

In [34]:
s1.std()

31.144823004794873

In [35]:
arr

array([324,  45,  67,  78,  56])

In [36]:
arr1 = np.array([1,2,3,4,5])

In [37]:
arr

array([324,  45,  67,  78,  56])

In [38]:
arr1

array([1, 2, 3, 4, 5])

In [39]:
arr + arr1

array([325,  47,  70,  82,  61])

In [40]:
s1

A    100
B     20
C     30
D     40
E     50
dtype: int64

In [41]:
s2 = pd.Series([1,2,3,4,5])
s2

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [42]:
s1


A    100
B     20
C     30
D     40
E     50
dtype: int64

In [43]:
s2

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [44]:
s1 + s2

A   NaN
B   NaN
C   NaN
D   NaN
E   NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
dtype: float64

In [45]:
s1

A    100
B     20
C     30
D     40
E     50
dtype: int64

In [46]:
s2 = pd.Series([1,2,3,4,5], index=['A', 'B', 'C', 'D', 'E'])
s2

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [47]:
s1

A    100
B     20
C     30
D     40
E     50
dtype: int64

In [48]:
s2

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [49]:
s1 + s2

A    101
B     22
C     33
D     44
E     55
dtype: int64

In [50]:
s1

A    100
B     20
C     30
D     40
E     50
dtype: int64

In [51]:
s1 + 10

A    110
B     30
C     40
D     50
E     60
dtype: int64

In [52]:
s1 / 10

A    10.0
B     2.0
C     3.0
D     4.0
E     5.0
dtype: float64

In [53]:
s1  * 20

A    2000
B     400
C     600
D     800
E    1000
dtype: int64

### Dataframe

In [54]:
df = pd.DataFrame({
    'salary':np.random.randint(30, 90, 20),
    'height':np.random.randint(120, 190, 20),
    'weight':np.random.randint(40, 90, 20),
    'age': np.random.randint(20, 35, 20),
    'country':np.random.choice(['india', 'usa', 'aus', 'china'], 20),
    'gender': np.random.choice(['male', 'female'], 20)
})
df

,salary,height,weight,age,country,gender
0,75,185,55,27,india,female
1,55,143,43,33,china,male
2,59,184,60,25,aus,male
3,71,137,55,20,usa,female
4,34,151,46,33,usa,female
5,82,185,71,26,india,female
6,80,162,44,26,india,female
7,59,134,87,29,china,male
8,58,179,48,33,usa,female
9,57,133,43,22,india,female


In [55]:
df.shape

(20, 6)

In [56]:
df.size

120

In [57]:
df.ndim

2

In [58]:
df.dtypes

salary      int32
height      int32
weight      int32
age         int32
country    object
gender     object
dtype: object

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   salary   20 non-null     int32 
 1   height   20 non-null     int32 
 2   weight   20 non-null     int32 
 3   age      20 non-null     int32 
 4   country  20 non-null     object
 5   gender   20 non-null     object
dtypes: int32(4), object(2)
memory usage: 772.0+ bytes


In [60]:
df.describe()

,salary,height,weight,age
count,20.000000,20.000000,20.000000,20.000000
mean,64.150000,160.600000,60.850000,26.850000
std,14.452372,20.288446,14.647705,4.704701
min,34.000000,133.000000,42.000000,20.000000
25%,55.000000,142.250000,47.500000,22.750000
50%,61.500000,157.500000,59.000000,26.000000
75%,76.000000,179.000000,70.250000,31.250000
max,85.000000,185.000000,87.000000,33.000000


In [61]:
df

,salary,height,weight,age,country,gender
0,75,185,55,27,india,female
1,55,143,43,33,china,male
2,59,184,60,25,aus,male
3,71,137,55,20,usa,female
4,34,151,46,33,usa,female
5,82,185,71,26,india,female
6,80,162,44,26,india,female
7,59,134,87,29,china,male
8,58,179,48,33,usa,female
9,57,133,43,22,india,female


In [62]:
df.head() # This will display the first 5 rows of the DataFrame df. It is useful for quickly inspecting the data and getting an overview of its structure and contents.

,salary,height,weight,age,country,gender
0,75,185,55,27,india,female
1,55,143,43,33,china,male
2,59,184,60,25,aus,male
3,71,137,55,20,usa,female
4,34,151,46,33,usa,female


In [63]:
df.head(7)

,salary,height,weight,age,country,gender
0,75,185,55,27,india,female
1,55,143,43,33,china,male
2,59,184,60,25,aus,male
3,71,137,55,20,usa,female
4,34,151,46,33,usa,female
5,82,185,71,26,india,female
6,80,162,44,26,india,female


In [64]:
df.tail() # This will display the last 5 rows of the DataFrame df. It is useful for quickly inspecting the data and getting an overview of its structure and contents.

,salary,height,weight,age,country,gender
15,64,178,85,20,india,male
16,50,177,54,31,usa,male
17,76,179,70,26,usa,male
18,80,153,69,22,india,male
19,43,152,71,31,china,male


In [65]:
df.tail(2)

,salary,height,weight,age,country,gender
18,80,153,69,22,india,male
19,43,152,71,31,china,male


In [66]:
df

,salary,height,weight,age,country,gender
0,75,185,55,27,india,female
1,55,143,43,33,china,male
2,59,184,60,25,aus,male
3,71,137,55,20,usa,female
4,34,151,46,33,usa,female
5,82,185,71,26,india,female
6,80,162,44,26,india,female
7,59,134,87,29,china,male
8,58,179,48,33,usa,female
9,57,133,43,22,india,female


In [67]:
df['salary']

0     75
1     55
2     59
3     71
4     34
5     82
6     80
7     59
8     58
9     57
10    76
11    55
12    85
13    76
14    48
15    64
16    50
17    76
18    80
19    43
Name: salary, dtype: int32

In [68]:
df['height']

0     185
1     143
2     184
3     137
4     151
5     185
6     162
7     134
8     179
9     133
10    134
11    185
12    144
13    140
14    177
15    178
16    177
17    179
18    153
19    152
Name: height, dtype: int32

In [69]:
df['gender']

0     female
1       male
2       male
3     female
4     female
5     female
6     female
7       male
8     female
9     female
10      male
11    female
12      male
13      male
14      male
15      male
16      male
17      male
18      male
19      male
Name: gender, dtype: object

In [72]:
df['gender'].value_counts()

gender
male      12
female     8
Name: count, dtype: int64

In [73]:
df['country'].value_counts()

country
india    7
usa      7
china    3
aus      3
Name: count, dtype: int64

In [75]:
df['country'].unique()

array(['india', 'china', 'aus', 'usa'], dtype=object)

In [76]:
df['country'].nunique()

4

In [77]:
df

,salary,height,weight,age,country,gender
0,75,185,55,27,india,female
1,55,143,43,33,china,male
2,59,184,60,25,aus,male
3,71,137,55,20,usa,female
4,34,151,46,33,usa,female
5,82,185,71,26,india,female
6,80,162,44,26,india,female
7,59,134,87,29,china,male
8,58,179,48,33,usa,female
9,57,133,43,22,india,female


In [78]:
df['salary']

0     75
1     55
2     59
3     71
4     34
5     82
6     80
7     59
8     58
9     57
10    76
11    55
12    85
13    76
14    48
15    64
16    50
17    76
18    80
19    43
Name: salary, dtype: int32

In [80]:
df

,salary,height,weight,age,country,gender
0,75,185,55,27,india,female
1,55,143,43,33,china,male
2,59,184,60,25,aus,male
3,71,137,55,20,usa,female
4,34,151,46,33,usa,female
5,82,185,71,26,india,female
6,80,162,44,26,india,female
7,59,134,87,29,china,male
8,58,179,48,33,usa,female
9,57,133,43,22,india,female


In [81]:
df[['salary', 'age', 'country']]

,salary,age,country
0,75,27,india
1,55,33,china
2,59,25,aus
3,71,20,usa
4,34,33,usa
5,82,26,india
6,80,26,india
7,59,29,china
8,58,33,usa
9,57,22,india


    indexing 
            iloc   --> int locations
                        default indexes
                        df.iloc[row_index, col_index]

            
            loc   --> label indexes eg. salary, age etc
                        df.loc[row_index, col_index]
            



    slicing

            iloc   --> int locations
                        default indexes
                        df.iloc[row_slicing, col_slicing]

            
            loc   --> label indexes
                        df.loc[row_slicing, col_slicing]

In [82]:
df = pd.DataFrame({
    'salary':np.random.randint(30, 90, 20),
    'height':np.random.randint(120, 190, 20),
    'weight':np.random.randint(40, 90, 20),
    'age': np.random.randint(20, 35, 20),
    'country':np.random.choice(['india', 'usa', 'aus', 'china'], 20),
    'gender': np.random.choice(['male', 'female'], 20)
}, index=[chr(i) for i in range(65, 65+20)])
df

,salary,height,weight,age,country,gender
A,53,170,64,29,aus,female
B,51,150,80,24,china,male
C,82,157,68,25,usa,male
D,87,157,75,32,aus,male
E,84,187,86,29,india,male
F,83,120,45,29,aus,female
G,80,144,76,24,aus,male
H,88,145,68,32,china,male
I,50,182,71,34,china,male
J,36,148,47,26,usa,male


In [83]:
df

,salary,height,weight,age,country,gender
A,53,170,64,29,aus,female
B,51,150,80,24,china,male
C,82,157,68,25,usa,male
D,87,157,75,32,aus,male
E,84,187,86,29,india,male
F,83,120,45,29,aus,female
G,80,144,76,24,aus,male
H,88,145,68,32,china,male
I,50,182,71,34,china,male
J,36,148,47,26,usa,male


In [84]:
chr(65)

'A'

In [85]:
for i in range(65, 65+20):
    print(chr(i))

A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T


In [86]:
df

,salary,height,weight,age,country,gender
A,53,170,64,29,aus,female
B,51,150,80,24,china,male
C,82,157,68,25,usa,male
D,87,157,75,32,aus,male
E,84,187,86,29,india,male
F,83,120,45,29,aus,female
G,80,144,76,24,aus,male
H,88,145,68,32,china,male
I,50,182,71,34,china,male
J,36,148,47,26,usa,male


In [87]:
df.iloc[2, 0]

np.int32(82)

In [88]:
df.loc['C', 'salary']

np.int32(82)

In [89]:
df.iloc[2:8:2, 1::2]

,height,age,gender
C,157,25,male
E,187,29,male
G,144,24,male


In [90]:
df.loc['C':'I':2, 'height'::2]

,height,age,gender
C,157,25,male
E,187,29,male
G,144,24,male
I,182,34,male


In [91]:
df

,salary,height,weight,age,country,gender
A,53,170,64,29,aus,female
B,51,150,80,24,china,male
C,82,157,68,25,usa,male
D,87,157,75,32,aus,male
E,84,187,86,29,india,male
F,83,120,45,29,aus,female
G,80,144,76,24,aus,male
H,88,145,68,32,china,male
I,50,182,71,34,china,male
J,36,148,47,26,usa,male


In [92]:
df.loc['D', 'salary'] = 67

In [93]:
df

,salary,height,weight,age,country,gender
A,53,170,64,29,aus,female
B,51,150,80,24,china,male
C,82,157,68,25,usa,male
D,67,157,75,32,aus,male
E,84,187,86,29,india,male
F,83,120,45,29,aus,female
G,80,144,76,24,aus,male
H,88,145,68,32,china,male
I,50,182,71,34,china,male
J,36,148,47,26,usa,male


# adding row & columns

In [94]:
df

,salary,height,weight,age,country,gender
A,53,170,64,29,aus,female
B,51,150,80,24,china,male
C,82,157,68,25,usa,male
D,67,157,75,32,aus,male
E,84,187,86,29,india,male
F,83,120,45,29,aus,female
G,80,144,76,24,aus,male
H,88,145,68,32,china,male
I,50,182,71,34,china,male
J,36,148,47,26,usa,male


In [95]:
df['new'] = np.random.randint(23,56,20)

In [96]:
df

,salary,height,weight,age,country,gender,new
A,53,170,64,29,aus,female,32
B,51,150,80,24,china,male,51
C,82,157,68,25,usa,male,28
D,67,157,75,32,aus,male,30
E,84,187,86,29,india,male,55
F,83,120,45,29,aus,female,35
G,80,144,76,24,aus,male,50
H,88,145,68,32,china,male,37
I,50,182,71,34,china,male,27
J,36,148,47,26,usa,male,37


In [97]:
df.loc['S']

salary       39
height      157
weight       85
age          20
country     usa
gender     male
new          55
Name: S, dtype: object

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, A to T
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   salary   20 non-null     int32 
 1   height   20 non-null     int32 
 2   weight   20 non-null     int32 
 3   age      20 non-null     int32 
 4   country  20 non-null     object
 5   gender   20 non-null     object
 6   new      20 non-null     int32 
dtypes: int32(5), object(2)
memory usage: 1.4+ KB


In [99]:
df.loc['Z'] = [34, 189, 78, 24, 'usa', 'female', 55]

In [100]:
df

,salary,height,weight,age,country,gender,new
A,53,170,64,29,aus,female,32
B,51,150,80,24,china,male,51
C,82,157,68,25,usa,male,28
D,67,157,75,32,aus,male,30
E,84,187,86,29,india,male,55
F,83,120,45,29,aus,female,35
G,80,144,76,24,aus,male,50
H,88,145,68,32,china,male,37
I,50,182,71,34,china,male,27
J,36,148,47,26,usa,male,37


In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21 entries, A to Z
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   salary   21 non-null     int64 
 1   height   21 non-null     int64 
 2   weight   21 non-null     int64 
 3   age      21 non-null     int64 
 4   country  21 non-null     object
 5   gender   21 non-null     object
 6   new      21 non-null     int64 
dtypes: int64(5), object(2)
memory usage: 1.9+ KB


# drop rows & columns

In [102]:
df

,salary,height,weight,age,country,gender,new
A,53,170,64,29,aus,female,32
B,51,150,80,24,china,male,51
C,82,157,68,25,usa,male,28
D,67,157,75,32,aus,male,30
E,84,187,86,29,india,male,55
F,83,120,45,29,aus,female,35
G,80,144,76,24,aus,male,50
H,88,145,68,32,china,male,37
I,50,182,71,34,china,male,27
J,36,148,47,26,usa,male,37


In [103]:
df.drop('salary')

KeyError: "['salary'] not found in axis"

In [104]:
df

,salary,height,weight,age,country,gender,new
A,53,170,64,29,aus,female,32
B,51,150,80,24,china,male,51
C,82,157,68,25,usa,male,28
D,67,157,75,32,aus,male,30
E,84,187,86,29,india,male,55
F,83,120,45,29,aus,female,35
G,80,144,76,24,aus,male,50
H,88,145,68,32,china,male,37
I,50,182,71,34,china,male,27
J,36,148,47,26,usa,male,37


In [105]:
df.drop('A')

,salary,height,weight,age,country,gender,new
B,51,150,80,24,china,male,51
C,82,157,68,25,usa,male,28
D,67,157,75,32,aus,male,30
E,84,187,86,29,india,male,55
F,83,120,45,29,aus,female,35
G,80,144,76,24,aus,male,50
H,88,145,68,32,china,male,37
I,50,182,71,34,china,male,27
J,36,148,47,26,usa,male,37
K,44,149,43,24,aus,male,47


In [ ]:
df.drop(['A', 'B', 'C', 'D']) # This will remove the columns 'A', 'B', 'C', and 'D' from the DataFrame df. temporary

,salary,height,weight,age,country,gender,new
E,84,187,86,29,india,male,55
F,83,120,45,29,aus,female,35
G,80,144,76,24,aus,male,50
H,88,145,68,32,china,male,37
I,50,182,71,34,china,male,27
J,36,148,47,26,usa,male,37
K,44,149,43,24,aus,male,47
L,88,184,56,34,india,female,24
M,64,146,71,22,china,female,53
N,80,168,71,24,india,male,39


In [107]:
df

,salary,height,weight,age,country,gender,new
A,53,170,64,29,aus,female,32
B,51,150,80,24,china,male,51
C,82,157,68,25,usa,male,28
D,67,157,75,32,aus,male,30
E,84,187,86,29,india,male,55
F,83,120,45,29,aus,female,35
G,80,144,76,24,aus,male,50
H,88,145,68,32,china,male,37
I,50,182,71,34,china,male,27
J,36,148,47,26,usa,male,37


In [108]:
df.drop('A', axis=0, inplace=True)

In [109]:
df

,salary,height,weight,age,country,gender,new
B,51,150,80,24,china,male,51
C,82,157,68,25,usa,male,28
D,67,157,75,32,aus,male,30
E,84,187,86,29,india,male,55
F,83,120,45,29,aus,female,35
G,80,144,76,24,aus,male,50
H,88,145,68,32,china,male,37
I,50,182,71,34,china,male,27
J,36,148,47,26,usa,male,37
K,44,149,43,24,aus,male,47


In [110]:
df.drop(['D', 'F', 'H'], inplace=True)

In [111]:
df

,salary,height,weight,age,country,gender,new
B,51,150,80,24,china,male,51
C,82,157,68,25,usa,male,28
E,84,187,86,29,india,male,55
G,80,144,76,24,aus,male,50
I,50,182,71,34,china,male,27
J,36,148,47,26,usa,male,37
K,44,149,43,24,aus,male,47
L,88,184,56,34,india,female,24
M,64,146,71,22,china,female,53
N,80,168,71,24,india,male,39


In [112]:
df.drop('salary', axis=1)

,height,weight,age,country,gender,new
B,150,80,24,china,male,51
C,157,68,25,usa,male,28
E,187,86,29,india,male,55
G,144,76,24,aus,male,50
I,182,71,34,china,male,27
J,148,47,26,usa,male,37
K,149,43,24,aus,male,47
L,184,56,34,india,female,24
M,146,71,22,china,female,53
N,168,71,24,india,male,39


In [113]:
df

,salary,height,weight,age,country,gender,new
B,51,150,80,24,china,male,51
C,82,157,68,25,usa,male,28
E,84,187,86,29,india,male,55
G,80,144,76,24,aus,male,50
I,50,182,71,34,china,male,27
J,36,148,47,26,usa,male,37
K,44,149,43,24,aus,male,47
L,88,184,56,34,india,female,24
M,64,146,71,22,china,female,53
N,80,168,71,24,india,male,39


In [114]:
df.drop('salary', axis=1, inplace=True)


In [115]:
df

,height,weight,age,country,gender,new
B,150,80,24,china,male,51
C,157,68,25,usa,male,28
E,187,86,29,india,male,55
G,144,76,24,aus,male,50
I,182,71,34,china,male,27
J,148,47,26,usa,male,37
K,149,43,24,aus,male,47
L,184,56,34,india,female,24
M,146,71,22,china,female,53
N,168,71,24,india,male,39


In [116]:
df.drop(['height', 'gender'], axis=1)

,weight,age,country,new
B,80,24,china,51
C,68,25,usa,28
E,86,29,india,55
G,76,24,aus,50
I,71,34,china,27
J,47,26,usa,37
K,43,24,aus,47
L,56,34,india,24
M,71,22,china,53
N,71,24,india,39


In [117]:
df

,height,weight,age,country,gender,new
B,150,80,24,china,male,51
C,157,68,25,usa,male,28
E,187,86,29,india,male,55
G,144,76,24,aus,male,50
I,182,71,34,china,male,27
J,148,47,26,usa,male,37
K,149,43,24,aus,male,47
L,184,56,34,india,female,24
M,146,71,22,china,female,53
N,168,71,24,india,male,39


### handling the missing values
#### there are 2 ways to handle the missing data
1. fill the missing values using central tendency / center of data
2. drop / delete the missing values. droping the data is not a good idea --> data loss

In [118]:
df

,height,weight,age,country,gender,new
B,150,80,24,china,male,51
C,157,68,25,usa,male,28
E,187,86,29,india,male,55
G,144,76,24,aus,male,50
I,182,71,34,china,male,27
J,148,47,26,usa,male,37
K,149,43,24,aus,male,47
L,184,56,34,india,female,24
M,146,71,22,china,female,53
N,168,71,24,india,male,39


In [120]:
df.isnull()

,height,weight,age,country,gender,new
B,False,False,False,False,False,False
C,False,False,False,False,False,False
E,False,False,False,False,False,False
G,False,False,False,False,False,False
I,False,False,False,False,False,False
J,False,False,False,False,False,False
K,False,False,False,False,False,False
L,False,False,False,False,False,False
M,False,False,False,False,False,False
N,False,False,False,False,False,False


In [121]:
df.isna()

,height,weight,age,country,gender,new
B,False,False,False,False,False,False
C,False,False,False,False,False,False
E,False,False,False,False,False,False
G,False,False,False,False,False,False
I,False,False,False,False,False,False
J,False,False,False,False,False,False
K,False,False,False,False,False,False
L,False,False,False,False,False,False
M,False,False,False,False,False,False
N,False,False,False,False,False,False


In [122]:
df.isna().sum()

height     0
weight     0
age        0
country    0
gender     0
new        0
dtype: int64

In [123]:
df

,height,weight,age,country,gender,new
B,150,80,24,china,male,51
C,157,68,25,usa,male,28
E,187,86,29,india,male,55
G,144,76,24,aus,male,50
I,182,71,34,china,male,27
J,148,47,26,usa,male,37
K,149,43,24,aus,male,47
L,184,56,34,india,female,24
M,146,71,22,china,female,53
N,168,71,24,india,male,39


In [124]:
df['height'].loc[::2] = np.nan
df['age'].loc[::4] = np.nan

C:\Users\Mayan\AppData\Local\Temp\ipykernel_25164\2124283467.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['height'].loc[::2] = np.nan
C:\Users\Mayan\AppData\Local\Temp\ipykernel_25164\2124283467.py:1: SettingWithCopyWarning: 
A val

In [125]:
df

,height,weight,age,country,gender,new
B,NaN,80,NaN,china,male,51
C,157.0,68,25.0,usa,male,28
E,NaN,86,29.0,india,male,55
G,144.0,76,24.0,aus,male,50
I,NaN,71,NaN,china,male,27
J,148.0,47,26.0,usa,male,37
K,NaN,43,24.0,aus,male,47
L,184.0,56,34.0,india,female,24
M,NaN,71,NaN,china,female,53
N,168.0,71,24.0,india,male,39


In [126]:
df.isna().sum()

height     9
weight     0
age        5
country    0
gender     0
new        0
dtype: int64

In [127]:
df.dropna(axis=0, how='any')

,height,weight,age,country,gender,new
C,157.0,68,25.0,usa,male,28
G,144.0,76,24.0,aus,male,50
J,148.0,47,26.0,usa,male,37
L,184.0,56,34.0,india,female,24
N,168.0,71,24.0,india,male,39
P,164.0,65,30.0,china,male,51
R,131.0,73,21.0,usa,female,29
T,185.0,60,23.0,usa,female,28


In [128]:
df

,height,weight,age,country,gender,new
B,NaN,80,NaN,china,male,51
C,157.0,68,25.0,usa,male,28
E,NaN,86,29.0,india,male,55
G,144.0,76,24.0,aus,male,50
I,NaN,71,NaN,china,male,27
J,148.0,47,26.0,usa,male,37
K,NaN,43,24.0,aus,male,47
L,184.0,56,34.0,india,female,24
M,NaN,71,NaN,china,female,53
N,168.0,71,24.0,india,male,39


In [129]:
df.dropna(axis=0, how='all')

,height,weight,age,country,gender,new
B,NaN,80,NaN,china,male,51
C,157.0,68,25.0,usa,male,28
E,NaN,86,29.0,india,male,55
G,144.0,76,24.0,aus,male,50
I,NaN,71,NaN,china,male,27
J,148.0,47,26.0,usa,male,37
K,NaN,43,24.0,aus,male,47
L,184.0,56,34.0,india,female,24
M,NaN,71,NaN,china,female,53
N,168.0,71,24.0,india,male,39


In [130]:
df.loc['z'] = np.nan

In [131]:
df

,height,weight,age,country,gender,new
B,NaN,80.0,NaN,china,male,51.0
C,157.0,68.0,25.0,usa,male,28.0
E,NaN,86.0,29.0,india,male,55.0
G,144.0,76.0,24.0,aus,male,50.0
I,NaN,71.0,NaN,china,male,27.0
J,148.0,47.0,26.0,usa,male,37.0
K,NaN,43.0,24.0,aus,male,47.0
L,184.0,56.0,34.0,india,female,24.0
M,NaN,71.0,NaN,china,female,53.0
N,168.0,71.0,24.0,india,male,39.0


In [132]:
df.dropna(axis=0, how='all')

,height,weight,age,country,gender,new
B,NaN,80.0,NaN,china,male,51.0
C,157.0,68.0,25.0,usa,male,28.0
E,NaN,86.0,29.0,india,male,55.0
G,144.0,76.0,24.0,aus,male,50.0
I,NaN,71.0,NaN,china,male,27.0
J,148.0,47.0,26.0,usa,male,37.0
K,NaN,43.0,24.0,aus,male,47.0
L,184.0,56.0,34.0,india,female,24.0
M,NaN,71.0,NaN,china,female,53.0
N,168.0,71.0,24.0,india,male,39.0


In [133]:
df

,height,weight,age,country,gender,new
B,NaN,80.0,NaN,china,male,51.0
C,157.0,68.0,25.0,usa,male,28.0
E,NaN,86.0,29.0,india,male,55.0
G,144.0,76.0,24.0,aus,male,50.0
I,NaN,71.0,NaN,china,male,27.0
J,148.0,47.0,26.0,usa,male,37.0
K,NaN,43.0,24.0,aus,male,47.0
L,184.0,56.0,34.0,india,female,24.0
M,NaN,71.0,NaN,china,female,53.0
N,168.0,71.0,24.0,india,male,39.0


In [134]:
df.drop('z', inplace=True)

In [135]:
df

,height,weight,age,country,gender,new
B,NaN,80.0,NaN,china,male,51.0
C,157.0,68.0,25.0,usa,male,28.0
E,NaN,86.0,29.0,india,male,55.0
G,144.0,76.0,24.0,aus,male,50.0
I,NaN,71.0,NaN,china,male,27.0
J,148.0,47.0,26.0,usa,male,37.0
K,NaN,43.0,24.0,aus,male,47.0
L,184.0,56.0,34.0,india,female,24.0
M,NaN,71.0,NaN,china,female,53.0
N,168.0,71.0,24.0,india,male,39.0


In [137]:
df.dropna(axis=1)

,weight,country,gender,new
B,80.0,china,male,51.0
C,68.0,usa,male,28.0
E,86.0,india,male,55.0
G,76.0,aus,male,50.0
I,71.0,china,male,27.0
J,47.0,usa,male,37.0
K,43.0,aus,male,47.0
L,56.0,india,female,24.0
M,71.0,china,female,53.0
N,71.0,india,male,39.0


In [138]:
df

,height,weight,age,country,gender,new
B,NaN,80.0,NaN,china,male,51.0
C,157.0,68.0,25.0,usa,male,28.0
E,NaN,86.0,29.0,india,male,55.0
G,144.0,76.0,24.0,aus,male,50.0
I,NaN,71.0,NaN,china,male,27.0
J,148.0,47.0,26.0,usa,male,37.0
K,NaN,43.0,24.0,aus,male,47.0
L,184.0,56.0,34.0,india,female,24.0
M,NaN,71.0,NaN,china,female,53.0
N,168.0,71.0,24.0,india,male,39.0


In [139]:
df['height'].fillna(df['height'].mean(), inplace=True)

C:\Users\Mayan\AppData\Local\Temp\ipykernel_25164\3929414796.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['height'].fillna(df['height'].mean(), inplace=True)


In [140]:
df

,height,weight,age,country,gender,new
B,160.125,80.0,NaN,china,male,51.0
C,157.000,68.0,25.0,usa,male,28.0
E,160.125,86.0,29.0,india,male,55.0
G,144.000,76.0,24.0,aus,male,50.0
I,160.125,71.0,NaN,china,male,27.0
J,148.000,47.0,26.0,usa,male,37.0
K,160.125,43.0,24.0,aus,male,47.0
L,184.000,56.0,34.0,india,female,24.0
M,160.125,71.0,NaN,china,female,53.0
N,168.000,71.0,24.0,india,male,39.0
